### ISSUE TITLE
The debugger always stop in luaD_hook

### ISSUE THREAD

**Issue by bsqgm** [WheretIB/LuaDkmDebugger#12]
I am using project you provided in issues #7 , and add breakpoints like this:
![image](https://user-images.githubusercontent.com/37140581/117692571-bb250e00-b1ef-11eb-81d1-6575b96f2fda.png)
When I press F5, the debugger just step into ldo.c luaD_hook function, and never stop in lua file. In addition, I didn't add breakpoint at there. Here's the png:
![image](https://user-images.githubusercontent.com/37140581/117693177-54ecbb00-b1f0-11eb-9d3e-0ee90f0343d5.png)

The addin's version is v0.9.6.
Here is log file:
[lua_dkm_debug_log.txt](https://github.com/WheretIB/LuaDkmDebugger/files/6453683/lua_dkm_debug_log.txt)

Can you tell me how to solve this problem? Or Do I need provide other imformation?

Here's an example project for Visual Studio 2019 you provided:
[lua_dbg_example.zip](https://github.com/WheretIB/LuaDkmDebugger/files/6128474/lua_dbg_example.zip)

**Comment by WheretIB** [comment]
Can you check the extension menu:
![luadkm_menu](https://user-images.githubusercontent.com/7524683/119268733-f1558b00-bbfc-11eb-8a25-1ccbd0511c42.png)
'Show Hidden Frames (Test)' should be turned Off.

**Comment by bsqgm** [comment]
> Can you check the extension menu:
> ![luadkm_menu](https://user-images.githubusercontent.com/7524683/119268733-f1558b00-bbfc-11eb-8a25-1ccbd0511c42.png)
> 'Show Hidden Frames (Test)' should be turned Off.

Thank you for your solution. The problem is sovled.
