### ISSUE TITLE
Lua script list: add sorting and search field

### ISSUE THREAD

**Issue by Xottab-DUTY** [WheretIB/LuaDkmDebugger#15]
When there are many scripts it's hard to find a script, when scripts are sorted in 'as they loaded' order :)

**Comment by WheretIB** [comment]
Good idea and shouldn't be hard to implement.

**Comment by WheretIB** [comment]
This feature has been implemented and will be included in next release.

**Comment by WheretIB** [comment]
Fixed in bef4a8b2a6f417832d8ecf3ee5fada9ebfe045d5
Released in https://github.com/WheretIB/LuaDkmDebugger/releases/tag/v0.9.9
