### ISSUE TITLE
pythonDkmDebugger for python

### ISSUE THREAD

**Issue by brinkqiang** [WheretIB/LuaDkmDebugger#23]
Hello, LuaDkmDebugger is the best lua plugin I have ever used.
Now I am developing in python. Can you port a python version following the same principle? Because I based on my research on python I found that they have some things in common. For example, modularization, require module -> import module
luaopen + _modulename -> init + modulename
thx！

**Comment by fsfod** [comment]
That already exists as part of [Python tools for Visual Studio](https://github.com/microsoft/PTVS). The code from that extension was probably used as guide for writing LuaDkmDebugger. 
The debugger mode for it is shown here [Debug Python and C++ together](https://learn.microsoft.com/en-gb/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2022 ), it uses the same concord\DKM debugger system.
