### ISSUE TITLE
Cannot startup debugger

### ISSUE THREAD

**Issue by tkgamegroup** [WheretIB/LuaDkmDebugger#5]
It shows "The debugger's worker process (msvsmon.exe) unexpectedlly exited. Debuggering will be aborted."
Here's the log file:

> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 9789.4140625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 9790.4140625ms
> INFO: Check if Lua library is loaded at 9797.40625ms
> WARNING: Failed to find Lua library at 9911.3515625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 9911.3515625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 9941.328125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 9942.3203125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 9979.3046875ms
> INFO: Found kernel32 library at 9979.3046875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 9991.296875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 9996.2890625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 9997.2890625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10105.2265625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10106.2265625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10132.2109375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10132.2109375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10147.2109375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10148.2109375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10171.203125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10171.203125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10214.171875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10214.171875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10220.1640625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10220.1640625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10226.1640625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10226.1640625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10231.15625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10231.15625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10236.1640625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10237.15625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10242.1484375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10243.1484375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10249.15625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10250.1484375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10255.140625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10256.140625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10263.140625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10263.140625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10269.1328125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10270.1484375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10275.140625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10276.1328125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10285.1328125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10285.1328125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10293.1171875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10297.125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10302.1171875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10303.1171875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10307.125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10308.125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10313.1171875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10313.1171875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10318.109375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10318.109375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10323.109375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10323.109375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10330.1015625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10331.1015625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10339.1015625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10340.09375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10347.1015625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10348.09375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10357.0859375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10357.0859375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10370.0859375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10371.0859375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10379.0703125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10380.0859375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10398.0703125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10399.0703125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10457.0390625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10458.0390625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10482.0078125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10483.0234375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10497.015625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10497.015625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10517.9921875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10517.9921875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10548.9765625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 10549.9765625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 10619.9453125ms
> INFO: Check if Lua library is loaded at 10620.9453125ms
> INFO: Local symbols connection is not available at 10669.9140625ms

VS version: VS2019 Community Preview 16.8.0 Preview 2.0
System OS: Windows 10
Lua Version: Lua 5,4

**Comment by WheretIB** [comment]
Do you have a crash dump file available inside %AppData%\..\Local\CrashDumps folder from devenv.exe or msvsmon.exe?

**Comment by tkgamegroup** [comment]
I can't find such files in that folder.

**Comment by WheretIB** [comment]
I have uploaded a new release here on Github https://github.com/WheretIB/LuaDkmDebugger/releases/tag/v0.9.4
It contains additional error checking and a more detailed log information around the location where is seems to crash.
Can you install this update (using vsix installer manually) and provide a new log?

**Comment by tkgamegroup** [comment]
The new log is like:

> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98594.078125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98596.0625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98596.0625ms
> INFO: Check if Lua library is loaded at 98598.0703125ms
> ERROR: Failed to find lua_newstate with: TryGetDiaSymbols() enumSymbols.count 0 != 1 at 98660.0234375ms
> ERROR: Failed to find luaL_newstate with: TryGetDiaSymbols() enumSymbols.count 0 != 1 at 98661.03125ms
> WARNING: Failed to find Lua library at 98661.03125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98662.015625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98669.0078125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98669.0078125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98674.015625ms
> INFO: Found kernel32 library at 98674.015625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98676.0078125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98678.03125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98697ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98717.6640625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98717.6640625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98759.796875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98760.8125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98775.796875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98775.796875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98791.7890625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98792.78125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98834.765625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98835.765625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98838.7578125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98838.7578125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98840.7578125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98841.765625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98843.75ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98843.75ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98846.7578125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98847.7578125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98850.7578125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98850.7578125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98854.7578125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98854.7578125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98857.7421875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98857.7421875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98861.765625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98861.765625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98864.7421875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98864.7421875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98868.7421875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98869.75ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98872.7421875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98872.7421875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98896.71875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98897.734375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98900.7265625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98900.7265625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98904.71875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98905.71875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98908.7109375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98909.7109375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98913.71875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98913.71875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98917.7109375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98918.7109375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98923.71875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98923.71875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98928.703125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98929.703125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98935.7109375ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98936.703125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98940.703125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98941.6953125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98946.703125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98946.703125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98951.6953125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98952.6953125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98958.6953125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98959.6953125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98964.6875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98965.6875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98973.6875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98974.6875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98983.6953125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98984.6796875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 98994.6796875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 98995.6640625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 99183.5703125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 99184.5625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 99193.5546875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 99194.546875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 99222.546875ms
> INFO: Check if Lua library is loaded at 99223.5390625ms
> INFO: Local symbols connection is not available: Microsoft.VisualStudio.Debugger.DkmException: Error in the application.
>    at XapiExceptionProcessing.ThrowHR(Int32 code)
>    at Microsoft.VisualStudio.Debugger.DkmCustomMessage.SendLower()
>    at LuaDkmDebuggerComponent.LocalComponent.GetLuaLocations(DkmProcess process, DkmNativeModuleInstance nativeModuleInstance)
>    at LuaDkmDebuggerComponent.LocalComponent.Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad(DkmModuleInstance moduleInstance, DkmWorkList workList, DkmEventDescriptorS eventDescriptor) at 99260.5234375ms
> ERROR: Failed to find lua_newstate with: TryGetFunctionAddress() Unexpected error: Microsoft.VisualStudio.Debugger.DkmException: Error in the application.
>    at XapiExceptionProcessing.ThrowHR(Int32 code)
>    at Microsoft.VisualStudio.Debugger.Symbols.DkmModule.GetSymbolInterface(Guid InterfaceID)
>    at LuaDkmDebuggerComponent.AttachmentHelpers.TryGetDiaSymbols(DkmModuleInstance moduleInstance, String& error)
>    at LuaDkmDebuggerComponent.AttachmentHelpers.TryGetDiaFunctionSymbol(DkmNativeModuleInstance moduleInstance, String name, String& error)
>    at LuaDkmDebuggerComponent.AttachmentHelpers.TryGetFunctionAddress(DkmNativeModuleInstance moduleInstance, String name, String& error) at 99262.515625ms
> ERROR: Failed to find luaL_newstate with: TryGetFunctionAddress() Unexpected error: Microsoft.VisualStudio.Debugger.DkmException: Error in the application.
>    at XapiExceptionProcessing.ThrowHR(Int32 code)
>    at Microsoft.VisualStudio.Debugger.Symbols.DkmModule.GetSymbolInterface(Guid InterfaceID)
>    at LuaDkmDebuggerComponent.AttachmentHelpers.TryGetDiaSymbols(DkmModuleInstance moduleInstance, String& error)
>    at LuaDkmDebuggerComponent.AttachmentHelpers.TryGetDiaFunctionSymbol(DkmNativeModuleInstance moduleInstance, String name, String& error)
>    at LuaDkmDebuggerComponent.AttachmentHelpers.TryGetFunctionAddress(DkmNativeModuleInstance moduleInstance, String name, String& error) at 99262.515625ms
> WARNING: Failed to find Lua library at 99263.515625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 99263.515625ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 99277.5078125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 99278.5078125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 99284.5078125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 99284.5078125ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad begin at 99300.4921875ms
> INFO: IDkmModuleInstanceLoadNotification.OnModuleInstanceLoad finished at 99300.4921875ms
>

**Comment by tkgamegroup** [comment]
Hi, i got more details from debugging the debugger project.

In file LocalComponent.cs, line 2407. An exception(E_XAPI_REMOTE_CLOSED) will be thrown with the module lua54.dll.

**Comment by tkgamegroup** [comment]
Also i got some XAML binding failures, is that will cause the problem?
![2](https://user-images.githubusercontent.com/12348900/118079043-ea9f6a80-b3e9-11eb-800d-7d20e8df891a.png)

**Comment by WheretIB** [comment]
Hello, the XAML bindings shouldn't create a problem for the debugger component.

I still can't reproduce this issue to debug locally, can you tell me with what compiler flags the lua54.dll is built with?

I have provided a self-contained test project in another issue: https://github.com/WheretIB/LuaDkmDebugger/issues/7#issuecomment-797313877
If it's possible, can you check if debugging that fails the same way?

**Comment by tkgamegroup** [comment]
Oh, everything works now, seems like i am missing the pdb file for the lua.dll.
And i am wondering why pdb is necessary here.

**Comment by tkgamegroup** [comment]
I did some changes to let the 'getting lua functions' process run right after module loaded event (not to notify through DkmCustomMessage). I still can't figure it out why it throw an exception when call DkmCustomMessage.SendLower.

**Comment by tkgamegroup** [comment]
Ok, is pdb cause the problem.
