### ISSUE TITLE
Hello, can you provide an example that can be debugged.

### ISSUE THREAD

**Issue by brinkqiang** [WheretIB/LuaDkmDebugger#7]
Hello, can you provide an example that can be debugged. I tested several projects and it didn’t work. I will provide a case https://github.com/brinkqiang/dmlua

**Comment by WheretIB** [comment]
Here's an example project for Visual Studio 2019:
[lua_dbg_example.zip](https://github.com/WheretIB/LuaDkmDebugger/files/6128474/lua_dbg_example.zip)

Open 'test.lua' file in 'lua_application' project 'Source Files' filter, place some breakpoints and run.

**Comment by brinkqiang** [comment]
Still unable to debug, can you use ShareX to record animated gif to describe the debugging setup process? My development environment is vs2019-16.8.3/WIN10.

**Comment by brinkqiang** [comment]
![debug](https://user-images.githubusercontent.com/10229072/110944106-f71a2f00-8376-11eb-85f5-0f7ef8af9a19.png)

**Comment by brinkqiang** [comment]
![debug2](https://user-images.githubusercontent.com/10229072/110944199-17e28480-8377-11eb-9cb1-da5de816ef5e.png)

**Comment by brinkqiang** [comment]
After testing, I found that if you set a breakpoint in the lua_pcallk function in advance, you can debug it. Remove it and you can’t.

**Comment by brinkqiang** [comment]
![debug3](https://user-images.githubusercontent.com/10229072/110945530-bfac8200-8378-11eb-90fb-c43757ae2412.png)

**Comment by WheretIB** [comment]
Thank you for additional information, I have found that there might be a race condition between script load and Visual Studio breakpoint state refresh.
I'll investigate how this can be fixed.

**Comment by WheretIB** [comment]
Breakpoints at the start of a script that was executed immediately after load didn't have enough time to refresh.

Fix for this was added in https://github.com/WheretIB/LuaDkmDebugger/releases/tag/v0.9.5 release.
Marketplace extension will soon be updated.
