### ISSUE TITLE
Loading script list directly from Lua state

### ISSUE THREAD

**Issue by Xottab-DUTY** [WheretIB/LuaDkmDebugger#9]
Look at [Decoda](https://unknownworlds.com/decoda/) – it can load scripts directly from the Lua state, thus we don't need to even setup anything. Very needed feature. =)

**Comment by WheretIB** [comment]
This extension loads scripts directly from memory if the source file is not available.

Can you please provide more details for the scenario that doesn't work for you?

**Comment by Xottab-DUTY** [comment]
The sources are not available in the filesystem at all.
Because of that I can't really configure the extension, hence I can't open any script that I want and set a breakpoint to it.

This extension is missing (and it would be nice to add) a window with all loaded scripts. (all scripts – both that are successfully found in the file system and from memory if they are not found in file system)

**Comment by WheretIB** [comment]
List of scripts WIP:
![image](https://user-images.githubusercontent.com/7524683/112393841-5d526a80-8d04-11eb-834a-fa707faa5141.png)

**Comment by WheretIB** [comment]
Script list panel can be displayed using 'Show Script list' menu option in [v0.9.6](https://github.com/WheretIB/LuaDkmDebugger/releases/tag/v0.9.6) release.
Update will be available in the Marketplace a bit later.
